import Head from "next/head";
import { useSelector } from "react-redux";
import Crew from "../components/Crew";
import SideMenu from "../components/SideMenu";

function crew() {
    const menuState = useSelector((state) => state.menu)
  return (
    <>
    <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/galaxy.png" />
    </Head>
    <Crew/>
    {menuState && <SideMenu/>}
    </>
  );
}

export default crew;
