import { Head } from "next/document";
import Crew from "../components/Crew";

function crew() {
  return (
    <>
    {/* <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/galaxy.png" />
    </Head> */}
    <Crew/>
    </>
  );
}

export default crew;
