import Head from "next/head"
import { useSelector } from "react-redux"
import Destination from "../components/Destination"
import SideMenu from "../components/SideMenu"

const destination = () => {
  const menuState = useSelector((state) => state.menu)
  return (
  <>
  <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/galaxy.png" />
    </Head>
  <Destination/>
  {menuState && <SideMenu/>}
  </>
  )
}

export default destination