import Head from 'next/head'
import { useSelector } from 'react-redux';
import Homepage from '../components/Homepage'
import SideMenu from '../components/SideMenu';

export default function Home() {
  const menuState = useSelector((state) => state.menu)
  return (
    <div>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/galaxy.png" />
      </Head>
      <main className='h-screen w-screen overflow-x-hidden'>
        <Homepage/>
        {menuState && <SideMenu/>}
      </main>
    </div>
  )
}
