import Head from 'next/head'
import Homepage from '../components/Homepage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/galaxy.png" />
      </Head>
      <main className='h-screen w-screen'>
        <Homepage/>
      </main>
    </div>
  )
}
