import Head from 'next/head'
import React from 'react'
import { useSelector } from 'react-redux'
import SideMenu from '../components/SideMenu'
import Technology from '../components/Technology'

function technology() {

    const menuState = useSelector((state) => state.menu)

  return (
    <>
    <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/galaxy.png" />
    </Head>
    <Technology/>
    {menuState && <SideMenu/>}
    </>
  )
}

export default technology